---
- name: Create VLANs on switches
  hosts: router
  gather_facts: no
  tasks:
    - name: Create VLAN
      cisco.ios.ios_config:
        lines:
          - "vlan {{ item.vlan_id }}"
          - "name {{ item.name }}"
        parents: []
      loop: "{{ vlans }}"
 