---
- name: Create VLANs
  hosts: switches
  gather_facts: no
  tasks:
    - name: Configure VLANs
      ios_config:
        lines:
          - vlan {{ item.vlan_id }}
          - name {{ item.name }}
      with_items: "{{ vlans }}"
